apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: jobscout
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "dev_access_secret_change_me_123"
  JWT_REFRESH_SECRET: "dev_refresh_secret_change_me_456"
  POSTGRES_PASSWORD: "postgres"
  RABBITMQ_PASSWORD: "rabbitmq_dev_password"
